# Generated by Django 3.0.8 on 2020-07-29 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='item',
            name='item_priority',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], max_length=100),
        ),
        migrations.AddField(
            model_name='todolist',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='list_type',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Trabalho', 'Trabalho'), ('Universidade', 'Universidade'), ('Hobby', 'Hobby'), ('Outro', 'Outro')], max_length=100),
        ),
    ]
