# Generated by Django 3.0.8 on 2020-07-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200729_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline_date',
            field=models.DateTimeField(null=True),
        ),
    ]
