# Generated by Django 3.0.8 on 2020-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200731_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default='none', null=True),
        ),
    ]
